# Generated by Django 5.0.8 on 2024-08-09 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comments_create_date_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 23, 53, 0, 177600, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 23, 53, 0, 177311, tzinfo=datetime.timezone.utc)),
        ),
    ]
