# Generated by Django 5.0.8 on 2024-08-09 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comments_create_date_alter_post_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_data',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 23, 53, 42, 27662, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 23, 53, 42, 27303, tzinfo=datetime.timezone.utc)),
        ),
    ]
