# Generated by Django 5.0.8 on 2024-08-13 00:47

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_quill.fields.QuillField(default='ici'),
        ),
    ]
